server:
  port: 8183
  servlet:
    context-path: /test

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_test
    username: sicollecte
    password: sicollecte
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true